import { Inter } from 'next/font/google'
import { Quicksand, Roboto, Poppins } from 'next/font/google'
import './globals.scss';
import Header from '../components/Header/Header';
import 'bootstrap/dist/css/bootstrap.css';


const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
    subsets: ['latin'],
    weight: '400',
})
const quicksand = Quicksand({
    subsets: ['latin'],
    weight: [
        '400',
        '500',
        '700',
        // '900'
    ],
})

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600', '700', '800', '900']
})


export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main className={poppins.className}>
                {children}
                </main>
            </body>
        </html>
    )
}
